server:
  port: 8088

jwt:
  secret: qinghe-mall-secret-key-2024
  expiration: 7200000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
      config:
        enabled: false
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: goods-service
          uri: http://127.0.0.1:8011
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=1
        - id: cart-service
          uri: http://127.0.0.1:8021
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://127.0.0.1:8031
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: pay-service
          uri: http://127.0.0.1:8041
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1
        - id: marketing-service
          uri: http://127.0.0.1:8051
          predicates:
            - Path=/api/marketing/**
          filters:
            - StripPrefix=1
